### ISSUE TITLE
Telegram notifications stop working:

### ISSUE THREAD

**Issue by sw33tT** [SeydX/homebridge-washingmachine-pow#4]
Plugin v2.0.2 worked without any issues.
With the update to v2.0.5 notifications stop working for me.

I edited the telegram.js file like in your Commits from 18.Nov - but still the same problem. No notifications over telegram. 

Homebridge v1.2.3, Node 14.15.1 LTS 

{
            "name": "WMPow",
            "debug": false,
            "devices": [
                {
                    "name": "Waschmaschine",
                    "ip": "xxx.xxx.xxx.xx“,
                    "port": 1883,
                    "manufacturer": "xxxx",
                    "model": "xxxx“,
                    "onValue": "ON",
                    "offValue": "OFF",
                    "startValue": 3,
                    "motionSensor": false,
                    "topics": {
                        "stateGet": "tele/Waschmaschine/STATE",
                        "statusGet": "stat/Waschmaschine/POWER",
                        "energyGet": "tele/Waschmaschine/SENSOR",
                        "statusSet": "cmnd/Waschmaschine/power",
                        "resetSet": [
                            "cmnd/Waschmaschine/EnergyReset1",
                            "cmnd/Waschmaschine/EnergyReset2",
                            "cmnd/Waschmaschine/EnergyReset3"
                        ]
                    }
                }
            ],
            "telegram": {
                "active": true,
                "token": "xxxx",
                "chatID": "xxxx",
                "messages": {
                    "started": "Waschmaschine: GESTARTET.",
                    "finished": "Waschmaschine: BEENDET!"
                }
            },
            "platform": "WMPow"
        }

**Comment by seydx** [comment]
@sw33tT 

thx for reporting. Fixed in v2.0.6

**Note**

If your washing machine is currently running, you will receive a notification when it is finished. It should then work as expected.

**Comment by sw33tT** [comment]
after update to v2.0.6 telegram notifications are back 👌

thanks 👍
